language: node_js
node_js:
  - "8.10"

deploy_service_job:
  cache:
    directories:
      - node_modules
      - backend/node_modules

  install:
    - npm install -g serverless
    - travis_retry npm install
    - cd backend
    - travis_retry npm install
    - cd -

  script:
    - cd $backend
    - serverless deploy -v
    - cd -