service:
  name: serverless-wyr-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  # tracing:
  #   lambda: true
  #   apiGateway: true
  # iamRoleStatements:           
  #     - Effect: 'Allow'
  #       Action:
  #         - 'xray:PutTraceSegments'
  #         - 'xray:PutTelemetryRecords'
  #       Resource:
  #         - '*'
  name: aws
  runtime: nodejs12.x
  
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    QUESTIONS_TABLE: Questions-${self:provider.stage}

functions:
  GetQuestions:
    handler: src/lambda/http/getQuestions.handler
    events:
      - http:
          method: get
          path: questions
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.QUESTIONS_TABLE}

resources:
  Resources:
    QuestionsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: questionId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: questionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.QUESTIONS_TABLE}